# Generated by Django 2.2.3 on 2019-07-31 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('art', '0004_art_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='likes',
        ),
        migrations.AddField(
            model_name='art',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_arts', models.ManyToManyField(blank=True, related_name='likes_users', to='art.Art')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
