# Generated by Django 2.2.3 on 2019-07-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0006_art_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
