# Generated by Django 2.2.3 on 2019-08-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0009_art_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='price',
            field=models.TextField(default='', max_length=50),
        ),
    ]
